# Generated by Django 6.0.2 on 2026-02-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_transaction_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(max_length=100),
        ),
    ]
