# Generated by Django 6.0.2 on 2026-02-24 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_transaction_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
